export const STAGE_TOPICS = {
    1: 'Basic Lending Terms',
    2: 'Interest Rates & APR',
    3: 'Collateral & Secured Lending',
    4: 'Property Appraisals & Valuations',
    5: 'Escrow, Closing & Title',
    6: 'LTV Ratios & Calculations',
    7: 'Defaults, Foreclosure Basics & Risk',
    8: 'Underwriting & Borrower Evaluation',
    9: 'Foreclosure Process & REO',
    10: 'After Repair Value & Advanced Concepts'
};

export const QUESTIONS = [
    // STAGE 1: The Loan Goblin - Basic Lending Terms
    { id:1, stage:1, type:"multiple_choice", question:"What is a hard money loan?", options:["A short-term loan secured by real property","A government-backed student loan","A credit card cash advance"], correctIndex:0, explanation:"Hard money loans are short-term loans backed by real estate, funded by private investors." },
    { id:2, stage:1, type:"true_false", question:"Hard money loans are typically funded by banks.", options:["True","False"], correctIndex:1, explanation:"Hard money loans are funded by private investors or companies, not traditional banks." },
    { id:3, stage:1, type:"multiple_choice", question:"What does 'principal' mean in lending?", options:["The interest rate","The original amount borrowed","The monthly payment"], correctIndex:1, explanation:"Principal is the original sum of money borrowed, before interest." },
    { id:4, stage:1, type:"true_false", question:"Hard money loans are usually short-term (1-3 years).", options:["True","False"], correctIndex:0, explanation:"Most hard money loans have terms of 6 months to 3 years." },
    { id:5, stage:1, type:"multiple_choice", question:"Who is the 'borrower' in a loan?", options:["The person lending money","The person receiving the loan","The real estate agent"], correctIndex:1, explanation:"The borrower is the person or entity that receives the loan funds." },
    { id:6, stage:1, type:"multiple_choice", question:"What is another name for the lender in hard money?", options:["Private lender","Federal agent","Mortgage broker"], correctIndex:0, explanation:"Hard money lenders are often called private lenders since they use private capital." },
    { id:7, stage:1, type:"true_false", question:"Hard money loans can close faster than bank loans.", options:["True","False"], correctIndex:0, explanation:"Hard money loans can close in days, while bank loans often take 30-60 days." },
    { id:8, stage:1, type:"multiple_choice", question:"What does 'term' mean for a loan?", options:["The interest rate charged","The length of time to repay","The property address"], correctIndex:1, explanation:"The term is the duration of the loan — how long you have to repay it." },
    { id:9, stage:1, type:"multiple_choice", question:"Hard money loans are most commonly used for:", options:["Buying groceries","Real estate investments","Paying off student loans"], correctIndex:1, explanation:"Hard money loans are primarily used for real estate investment and property transactions." },
    { id:10, stage:1, type:"true_false", question:"A promissory note is a written promise to repay a loan.", options:["True","False"], correctIndex:0, explanation:"A promissory note is a legal document where the borrower promises to repay the lender." },

    // STAGE 2: The Interest Rate Imp - Interest Rates & APR
    { id:11, stage:2, type:"multiple_choice", question:"Typical hard money interest rates are:", options:["1-3%","8-15%","25-30%"], correctIndex:1, explanation:"Hard money loans typically carry interest rates between 8% and 15%." },
    { id:12, stage:2, type:"multiple_choice", question:"What does APR stand for?", options:["Annual Percentage Rate","Approved Property Rating","Adjusted Payment Ratio"], correctIndex:0, explanation:"APR stands for Annual Percentage Rate — the total yearly cost of borrowing." },
    { id:13, stage:2, type:"true_false", question:"APR includes both interest and fees.", options:["True","False"], correctIndex:0, explanation:"APR reflects the true cost of borrowing by including interest rate plus fees." },
    { id:14, stage:2, type:"multiple_choice", question:"What is 1 'point' on a loan?", options:["1% of the loan amount","$1,000 flat fee","1% of the property value"], correctIndex:0, explanation:"One point equals 1% of the loan amount, charged as an upfront fee." },
    { id:15, stage:2, type:"multiple_choice", question:"If you borrow $200,000 and pay 2 points, what's the fee?", options:["$2,000","$4,000","$20,000"], correctIndex:1, explanation:"2 points on $200,000 = 2% × $200,000 = $4,000." },
    { id:16, stage:2, type:"true_false", question:"Hard money rates are usually lower than bank rates.", options:["True","False"], correctIndex:1, explanation:"Hard money rates are higher than bank rates because of faster funding and higher risk." },
    { id:17, stage:2, type:"multiple_choice", question:"Why are hard money rates higher than bank rates?", options:["Lenders are greedy","Higher risk and faster funding","Government regulations"], correctIndex:1, explanation:"The higher rates compensate for increased risk and the speed of private lending." },
    { id:18, stage:2, type:"true_false", question:"Interest on hard money loans can be paid monthly or at maturity.", options:["True","False"], correctIndex:0, explanation:"Some hard money loans require monthly interest payments, others collect all interest at payoff." },
    { id:19, stage:2, type:"multiple_choice", question:"What is a 'prepayment penalty'?", options:["A fee for paying late","A fee for paying off the loan early","A fee for the appraisal"], correctIndex:1, explanation:"A prepayment penalty is charged when a borrower pays off the loan before the term ends." },
    { id:20, stage:2, type:"multiple_choice", question:"If a loan has 12% annual interest, what is the monthly rate?", options:["1%","6%","12%"], correctIndex:0, explanation:"Monthly rate = Annual rate ÷ 12, so 12% ÷ 12 = 1% per month." },

    // STAGE 3: The Collateral Crab - Collateral & Secured Lending
    { id:21, stage:3, type:"multiple_choice", question:"What is collateral?", options:["A type of insurance","An asset pledged to secure a loan","A closing document"], correctIndex:1, explanation:"Collateral is property or assets that a borrower offers to secure a loan." },
    { id:22, stage:3, type:"true_false", question:"Hard money loans are secured by real property.", options:["True","False"], correctIndex:0, explanation:"The real estate itself serves as collateral for hard money loans." },
    { id:23, stage:3, type:"multiple_choice", question:"What happens if a borrower defaults on a secured loan?", options:["Nothing happens","The lender can take the collateral","The rate goes down"], correctIndex:1, explanation:"If a borrower defaults, the lender can seize the collateral (the property) to recover the loan." },
    { id:24, stage:3, type:"multiple_choice", question:"A lien is:", options:["A type of property","A legal claim on property as security for a debt","A discount on the loan"], correctIndex:1, explanation:"A lien gives the lender a legal right to the property until the debt is paid." },
    { id:25, stage:3, type:"true_false", question:"Hard money lenders care more about the property than the borrower's credit score.", options:["True","False"], correctIndex:0, explanation:"Hard money lending is asset-based — the property value matters more than credit scores." },
    { id:26, stage:3, type:"multiple_choice", question:"What is a first lien position?", options:["The newest loan on a property","The loan with highest priority to be repaid","The smallest loan"], correctIndex:1, explanation:"First lien has priority — it gets paid first if the property is sold or foreclosed." },
    { id:27, stage:3, type:"true_false", question:"An unsecured loan has no collateral backing it.", options:["True","False"], correctIndex:0, explanation:"Unsecured loans have no collateral, unlike hard money loans which are always secured." },
    { id:28, stage:3, type:"multiple_choice", question:"What type of property can be used as collateral?", options:["Only single-family homes","Only commercial buildings","Residential, commercial, and land"], correctIndex:2, explanation:"Various property types can serve as collateral including homes, commercial, and raw land." },
    { id:29, stage:3, type:"true_false", question:"A second lien is riskier for the lender than a first lien.", options:["True","False"], correctIndex:0, explanation:"Second lien holders get paid after first lien holders, making it a riskier position." },
    { id:30, stage:3, type:"multiple_choice", question:"A deed of trust:", options:["Transfers property to the buyer","Secures the loan against the property","Is the same as a lease"], correctIndex:1, explanation:"A deed of trust is a security instrument that ties the loan to the property." },

    // STAGE 4: The Appraisal Ghost - Property Appraisals & Valuations
    { id:31, stage:4, type:"multiple_choice", question:"What is a property appraisal?", options:["A home inspection for defects","A professional estimate of a property's market value","A title search"], correctIndex:1, explanation:"An appraisal determines the fair market value of a property by a licensed appraiser." },
    { id:32, stage:4, type:"true_false", question:"Comparable sales (comps) are used to determine property value.", options:["True","False"], correctIndex:0, explanation:"Appraisers use recent sales of similar nearby properties to estimate value." },
    { id:33, stage:4, type:"multiple_choice", question:"What are 'comps' in real estate?", options:["Complaints about a property","Recently sold similar properties nearby","Computer-generated estimates"], correctIndex:1, explanation:"Comps are comparable properties that recently sold, used to estimate market value." },
    { id:34, stage:4, type:"multiple_choice", question:"Why do hard money lenders require appraisals?", options:["It's a way to charge more fees","To ensure the property value covers the loan","For decoration"], correctIndex:1, explanation:"Lenders need to verify the property is worth enough to secure the loan amount." },
    { id:35, stage:4, type:"true_false", question:"An appraisal and a home inspection are the same thing.", options:["True","False"], correctIndex:1, explanation:"An appraisal determines value; an inspection checks the physical condition of the property." },
    { id:36, stage:4, type:"multiple_choice", question:"Fair Market Value (FMV) is:", options:["The price a seller hopes to get","The price a willing buyer and seller agree upon","The original purchase price"], correctIndex:1, explanation:"FMV is what a property would sell for on the open market between willing parties." },
    { id:37, stage:4, type:"true_false", question:"A property's assessed value for taxes is always the same as its market value.", options:["True","False"], correctIndex:1, explanation:"Tax assessed value and market value are often different — assessed value may be lower." },
    { id:38, stage:4, type:"multiple_choice", question:"A BPO stands for:", options:["Broker Price Opinion","Bank Payment Order","Buyer's Purchase Offer"], correctIndex:0, explanation:"A BPO is a less formal property valuation done by a real estate broker." },
    { id:39, stage:4, type:"multiple_choice", question:"If similar homes in the area sold for $300K, $310K, and $290K, the property is likely worth around:", options:["$200,000","$300,000","$500,000"], correctIndex:1, explanation:"Comps averaging around $300K suggest the property value is in that range." },
    { id:40, stage:4, type:"true_false", question:"Location is one of the most important factors in property valuation.", options:["True","False"], correctIndex:0, explanation:"Location significantly impacts property value — it's the #1 factor in real estate." },

    // STAGE 5: The Escrow Ogre - Escrow, Closing & Title
    { id:41, stage:5, type:"multiple_choice", question:"What is escrow?", options:["A type of loan","A neutral third party that holds funds during a transaction","A property tax"], correctIndex:1, explanation:"Escrow is a neutral party that holds money and documents until all deal conditions are met." },
    { id:42, stage:5, type:"true_false", question:"Title insurance protects against ownership disputes.", options:["True","False"], correctIndex:0, explanation:"Title insurance protects the buyer and lender from claims against the property's ownership." },
    { id:43, stage:5, type:"multiple_choice", question:"What is a title search?", options:["Searching for a property online","Examining public records for ownership history","Choosing a name for your property"], correctIndex:1, explanation:"A title search reviews public records to verify clear ownership and find any liens." },
    { id:44, stage:5, type:"multiple_choice", question:"'Closing' in real estate refers to:", options:["Shutting down a property","The final step where ownership transfers","Closing a bank account"], correctIndex:1, explanation:"Closing is the final meeting where documents are signed and ownership officially transfers." },
    { id:45, stage:5, type:"true_false", question:"Closing costs only include the lender's fees.", options:["True","False"], correctIndex:1, explanation:"Closing costs include lender fees, title fees, escrow fees, recording fees, and more." },
    { id:46, stage:5, type:"multiple_choice", question:"A clear title means:", options:["The property has a nice name","There are no liens or ownership disputes","The house was recently painted"], correctIndex:1, explanation:"A clear title means no legal claims, liens, or disputes exist against the property." },
    { id:47, stage:5, type:"multiple_choice", question:"Who typically chooses the escrow company?", options:["The government","Usually agreed upon by buyer and seller","The neighbors"], correctIndex:1, explanation:"The escrow company is typically chosen by agreement between the parties in the transaction." },
    { id:48, stage:5, type:"true_false", question:"Recording a deed makes the property transfer part of public record.", options:["True","False"], correctIndex:0, explanation:"Recording the deed with the county officially documents the change of ownership." },
    { id:49, stage:5, type:"multiple_choice", question:"What is earnest money?", options:["Money the lender earns","A good-faith deposit from the buyer","The appraiser's fee"], correctIndex:1, explanation:"Earnest money shows the buyer is serious — it's a deposit held in escrow." },
    { id:50, stage:5, type:"true_false", question:"You can close on a hard money loan without an escrow company.", options:["True","False"], correctIndex:1, explanation:"Escrow companies are typically required to ensure a safe and proper closing process." },

    // STAGE 6: The LTV Werewolf - LTV Ratios & Calculations
    { id:51, stage:6, type:"multiple_choice", question:"What does LTV stand for?", options:["Loan-To-Value","Long-Term Variance","Lender Tax Verification"], correctIndex:0, explanation:"LTV stands for Loan-To-Value — the ratio of the loan amount to the property value." },
    { id:52, stage:6, type:"multiple_choice", question:"How do you calculate LTV?", options:["Property Value ÷ Loan Amount","Loan Amount ÷ Property Value","Loan Amount × Interest Rate"], correctIndex:1, explanation:"LTV = Loan Amount ÷ Property Value. A $150K loan on a $200K property = 75% LTV." },
    { id:53, stage:6, type:"true_false", question:"A lower LTV means less risk for the lender.", options:["True","False"], correctIndex:0, explanation:"Lower LTV means the loan is a smaller portion of the property value — more equity cushion." },
    { id:54, stage:6, type:"multiple_choice", question:"Most hard money lenders cap LTV at:", options:["90-100%","60-75%","10-20%"], correctIndex:1, explanation:"Hard money lenders typically lend up to 60-75% of the property's value." },
    { id:55, stage:6, type:"multiple_choice", question:"A $300,000 loan on a $400,000 property has what LTV?", options:["75%","60%","80%"], correctIndex:0, explanation:"$300,000 ÷ $400,000 = 0.75 = 75% LTV." },
    { id:56, stage:6, type:"true_false", question:"100% LTV means the loan covers the entire property value.", options:["True","False"], correctIndex:0, explanation:"100% LTV means no down payment — the loan equals the full property value (very risky)." },
    { id:57, stage:6, type:"multiple_choice", question:"If a property is worth $500,000 and the max LTV is 70%, what's the maximum loan?", options:["$350,000","$500,000","$250,000"], correctIndex:0, explanation:"$500,000 × 70% = $350,000 maximum loan amount." },
    { id:58, stage:6, type:"multiple_choice", question:"Why do hard money lenders keep LTV low?", options:["To annoy borrowers","To protect against losses if they need to sell the property","Because the law requires it"], correctIndex:1, explanation:"Low LTV ensures the lender can recover their money even if the property loses value." },
    { id:59, stage:6, type:"true_false", question:"A borrower's down payment reduces the LTV ratio.", options:["True","False"], correctIndex:0, explanation:"A larger down payment means a smaller loan relative to value — lower LTV." },
    { id:60, stage:6, type:"multiple_choice", question:"CLTV stands for:", options:["Combined Loan-To-Value","Current Lending Tax Value","Closed Loan Transfer Voucher"], correctIndex:0, explanation:"CLTV is Combined Loan-To-Value — it includes all loans against the property." },

    // STAGE 7: The Default Demon - Defaults, Foreclosure Basics & Risk
    { id:61, stage:7, type:"multiple_choice", question:"What does it mean to 'default' on a loan?", options:["To pay it off early","To fail to meet loan obligations","To refinance the loan"], correctIndex:1, explanation:"Default means the borrower has failed to make payments or meet other loan terms." },
    { id:62, stage:7, type:"true_false", question:"Missing one payment immediately triggers foreclosure.", options:["True","False"], correctIndex:1, explanation:"Typically lenders provide a grace period and notice before starting foreclosure proceedings." },
    { id:63, stage:7, type:"multiple_choice", question:"What is the main risk for a hard money lender?", options:["The borrower being too nice","The borrower defaulting and the property losing value","Interest rates going up"], correctIndex:1, explanation:"The biggest risk is default combined with a property worth less than the loan balance." },
    { id:64, stage:7, type:"multiple_choice", question:"A 'maturity default' occurs when:", options:["The borrower is too old","The loan term expires and the borrower can't repay","The property matures in value"], correctIndex:1, explanation:"Maturity default happens when the loan term ends and the borrower cannot pay it off." },
    { id:65, stage:7, type:"true_false", question:"Hard money lenders mitigate risk by keeping LTV ratios low.", options:["True","False"], correctIndex:0, explanation:"Low LTV ratios provide an equity cushion, reducing the lender's risk of loss." },
    { id:66, stage:7, type:"multiple_choice", question:"What is a loan modification?", options:["Changing the property","Changing the loan terms to help the borrower","Changing the lender"], correctIndex:1, explanation:"A loan modification adjusts terms like rate or duration to help a struggling borrower." },
    { id:67, stage:7, type:"true_false", question:"Diversifying across multiple loans reduces a lender's risk.", options:["True","False"], correctIndex:0, explanation:"Spreading investments across multiple loans means one default doesn't wipe out the lender." },
    { id:68, stage:7, type:"multiple_choice", question:"A 'notice of default' is:", options:["A friendly reminder","A formal notification that the borrower has violated loan terms","A receipt for payment"], correctIndex:1, explanation:"A notice of default is a formal document starting the pre-foreclosure process." },
    { id:69, stage:7, type:"multiple_choice", question:"What is an 'exit strategy'?", options:["A plan to leave a building","The borrower's plan to repay the loan","A type of insurance"], correctIndex:1, explanation:"An exit strategy is how the borrower plans to pay off the loan (sell, refinance, etc.)." },
    { id:70, stage:7, type:"true_false", question:"A borrower's exit strategy is important to hard money lenders.", options:["True","False"], correctIndex:0, explanation:"Lenders want to know how the borrower will repay — a clear exit strategy reduces risk." },

    // STAGE 8: The Underwriting Hydra - Underwriting & Borrower Evaluation
    { id:71, stage:8, type:"multiple_choice", question:"What is underwriting?", options:["Writing under a document","The process of evaluating loan risk","Signing the bottom of a check"], correctIndex:1, explanation:"Underwriting is the process of assessing the risk of making a loan." },
    { id:72, stage:8, type:"true_false", question:"Hard money underwriting focuses more on the property than the borrower's credit.", options:["True","False"], correctIndex:0, explanation:"Unlike banks, hard money lenders primarily evaluate the property and deal, not credit scores." },
    { id:73, stage:8, type:"multiple_choice", question:"What is a key factor in hard money underwriting?", options:["The borrower's favorite color","The property value and condition","The borrower's age"], correctIndex:1, explanation:"Property value, condition, and the deal's viability are the primary underwriting factors." },
    { id:74, stage:8, type:"multiple_choice", question:"A borrower's 'track record' refers to:", options:["Their running speed","Their experience with similar deals","Their music playlist"], correctIndex:1, explanation:"Experienced borrowers with successful past deals are considered lower risk." },
    { id:75, stage:8, type:"true_false", question:"Hard money lenders never look at a borrower's credit at all.", options:["True","False"], correctIndex:1, explanation:"While not the primary focus, many hard money lenders do a basic credit check." },
    { id:76, stage:8, type:"multiple_choice", question:"What does 'skin in the game' mean for a borrower?", options:["They have a sunburn","They have their own money invested in the deal","They work in a leather shop"], correctIndex:1, explanation:"Skin in the game means the borrower has invested their own capital, aligning interests." },
    { id:77, stage:8, type:"multiple_choice", question:"A 'scope of work' in hard money lending describes:", options:["The lender's job duties","The planned renovations and their costs","The borrower's employment history"], correctIndex:1, explanation:"The scope of work details what repairs/renovations will be done and at what cost." },
    { id:78, stage:8, type:"true_false", question:"A borrower's exit strategy is part of the underwriting process.", options:["True","False"], correctIndex:0, explanation:"Lenders evaluate the exit strategy to determine how and when they'll be repaid." },
    { id:79, stage:8, type:"multiple_choice", question:"Draw schedules are used to:", options:["Create artwork","Release renovation funds in stages as work is completed","Schedule meetings"], correctIndex:1, explanation:"Draw schedules release loan funds incrementally as renovation milestones are completed." },
    { id:80, stage:8, type:"true_false", question:"A hard money lender might inspect the property during renovation.", options:["True","False"], correctIndex:0, explanation:"Lenders often inspect progress before releasing additional renovation funds." },

    // STAGE 9: The Foreclosure Phoenix - Foreclosure Process & REO
    { id:81, stage:9, type:"multiple_choice", question:"What is foreclosure?", options:["Closing a gate","The legal process of taking property from a defaulted borrower","A type of insurance claim"], correctIndex:1, explanation:"Foreclosure is the legal process where a lender takes ownership of property after default." },
    { id:82, stage:9, type:"multiple_choice", question:"What does REO stand for?", options:["Real Estate Owned","Really Expensive Offer","Regional Escrow Office"], correctIndex:0, explanation:"REO means Real Estate Owned — property owned by a lender after a failed foreclosure auction." },
    { id:83, stage:9, type:"true_false", question:"There are two types of foreclosure: judicial and non-judicial.", options:["True","False"], correctIndex:0, explanation:"Judicial foreclosure goes through court; non-judicial follows a power of sale clause." },
    { id:84, stage:9, type:"multiple_choice", question:"A foreclosure auction is:", options:["A party at the courthouse","A public sale of the foreclosed property","A private meeting with the borrower"], correctIndex:1, explanation:"At a foreclosure auction, the property is sold to the highest bidder to repay the debt." },
    { id:85, stage:9, type:"true_false", question:"The borrower can sometimes stop foreclosure by paying what's owed.", options:["True","False"], correctIndex:0, explanation:"Many states allow a redemption period where the borrower can pay off the debt to keep the property." },
    { id:86, stage:9, type:"multiple_choice", question:"A 'short sale' happens when:", options:["The sale takes a short time","The property sells for less than the loan balance with lender approval","The seller is short"], correctIndex:1, explanation:"In a short sale, the lender agrees to accept less than what's owed to avoid foreclosure." },
    { id:87, stage:9, type:"multiple_choice", question:"What is a 'deed in lieu of foreclosure'?", options:["A special type of deed","The borrower voluntarily transfers the property to the lender","A fake deed"], correctIndex:1, explanation:"A deed in lieu lets the borrower hand over the property to avoid formal foreclosure." },
    { id:88, stage:9, type:"true_false", question:"Foreclosure timelines vary by state.", options:["True","False"], correctIndex:0, explanation:"Each state has different foreclosure laws, and timelines can range from weeks to over a year." },
    { id:89, stage:9, type:"multiple_choice", question:"A 'workout' in lending means:", options:["Going to the gym","Negotiating alternatives to foreclosure","Working overtime"], correctIndex:1, explanation:"A workout is when lender and borrower negotiate alternatives like modification or repayment plans." },
    { id:90, stage:9, type:"true_false", question:"REO properties are often sold at a discount.", options:["True","False"], correctIndex:0, explanation:"REO properties often sell below market value since lenders want to recover their capital quickly." },

    // STAGE 10: The ARV Dragon - After Repair Value & Advanced Concepts
    { id:91, stage:10, type:"multiple_choice", question:"What does ARV stand for?", options:["After Repair Value","Annual Rate of Variance","Adjusted Real Value"], correctIndex:0, explanation:"ARV is the estimated value of a property AFTER renovations are completed." },
    { id:92, stage:10, type:"multiple_choice", question:"The 70% Rule says investors should pay no more than:", options:["70% of current value","70% of ARV minus repair costs","70% of the loan amount"], correctIndex:1, explanation:"The 70% Rule: Max Purchase = (ARV × 70%) - Repair Costs." },
    { id:93, stage:10, type:"true_false", question:"ARV is calculated BEFORE renovations are done.", options:["True","False"], correctIndex:0, explanation:"ARV is an estimate made before work begins, projecting what the property will be worth after." },
    { id:94, stage:10, type:"multiple_choice", question:"If a property has an ARV of $400,000, what's the max loan at 70% LTV?", options:["$280,000","$320,000","$400,000"], correctIndex:0, explanation:"$400,000 × 70% = $280,000 maximum loan amount." },
    { id:95, stage:10, type:"multiple_choice", question:"A 'fix and flip' strategy is:", options:["Fixing a pancake","Buying, renovating, and selling a property for profit","Flipping a coin to decide"], correctIndex:1, explanation:"Fix and flip means purchasing a property, renovating it, and selling at a higher price." },
    { id:96, stage:10, type:"true_false", question:"ARV is determined using comps of renovated properties in the area.", options:["True","False"], correctIndex:0, explanation:"ARV uses comparable sales of similar renovated properties to estimate post-repair value." },
    { id:97, stage:10, type:"multiple_choice", question:"Using the 70% rule: ARV is $500K, repairs cost $80K. Max purchase price?", options:["$270,000","$350,000","$420,000"], correctIndex:0, explanation:"($500,000 × 70%) - $80,000 = $350,000 - $80,000 = $270,000." },
    { id:98, stage:10, type:"multiple_choice", question:"What is a BRRRR strategy?", options:["Being cold","Buy, Rehab, Rent, Refinance, Repeat","Borrow, Return, Reinvest, Redo, Relax"], correctIndex:1, explanation:"BRRRR is a real estate strategy: Buy, Rehab, Rent, Refinance, and Repeat." },
    { id:99, stage:10, type:"true_false", question:"Hard money loans are commonly used to fund fix-and-flip projects.", options:["True","False"], correctIndex:0, explanation:"Fix-and-flip is one of the most common uses for hard money loans due to their short-term nature." },
    { id:100, stage:10, type:"multiple_choice", question:"What is 'equity' in a property?", options:["The property's total value","The difference between property value and what's owed","The monthly payment amount"], correctIndex:1, explanation:"Equity = Property Value - Loan Balance. It's the owner's actual stake in the property." },

    // ═══════════════════════════════════════════════════════════
    // ADDITIONAL QUESTIONS (8 per stage) — IDs 101-180
    // ═══════════════════════════════════════════════════════════

    // STAGE 1 EXTRA: Basic Lending Terms
    { id:101, stage:1, type:"multiple_choice", question:"What is a 'maturity date' on a loan?", options:["The date the borrower turns 18","The date the loan must be fully repaid","The date the property was built"], correctIndex:1, explanation:"The maturity date is when the loan term ends and the full balance is due." },
    { id:102, stage:1, type:"true_false", question:"Hard money loans typically have terms of 15-30 years.", options:["True","False"], correctIndex:1, explanation:"Hard money loans are short-term, usually 6 months to 3 years, not decades like traditional mortgages." },
    { id:103, stage:1, type:"multiple_choice", question:"A 'note' in lending refers to:", options:["A sticky note reminder","A legal document promising repayment","A type of property"], correctIndex:1, explanation:"A promissory note is the legal document where the borrower promises to repay the loan." },
    { id:104, stage:1, type:"multiple_choice", question:"Who typically uses hard money loans?", options:["First-time home buyers","Real estate investors and house flippers","College students"], correctIndex:1, explanation:"Hard money loans are primarily used by real estate investors who need fast funding for deals." },
    { id:105, stage:1, type:"true_false", question:"Hard money loans require extensive paperwork like bank loans.", options:["True","False"], correctIndex:1, explanation:"Hard money loans have simpler documentation requirements compared to traditional bank loans." },
    { id:106, stage:1, type:"multiple_choice", question:"What does 'funding' mean in the context of a loan?", options:["Raising money for charity","The lender disbursing the loan money","Saving money in a piggy bank"], correctIndex:1, explanation:"Funding is when the lender actually sends or releases the loan money to the borrower or escrow." },
    { id:107, stage:1, type:"true_false", question:"A hard money lender can be an individual person, not just a company.", options:["True","False"], correctIndex:0, explanation:"Hard money lenders can be individual private investors or lending companies with pooled funds." },
    { id:108, stage:1, type:"multiple_choice", question:"What is the main advantage of a hard money loan over a bank loan?", options:["Lower interest rates","Speed of funding and flexible terms","No repayment required"], correctIndex:1, explanation:"Hard money loans can close in days vs. weeks for banks, with more flexible approval criteria." },

    // STAGE 2 EXTRA: Interest Rates & APR
    { id:109, stage:2, type:"multiple_choice", question:"If a loan charges 10% annual interest on $100,000, how much interest accrues per month?", options:["$833","$1,000","$10,000"], correctIndex:0, explanation:"$100,000 × 10% ÷ 12 months = $833.33 per month." },
    { id:110, stage:2, type:"true_false", question:"Points are paid at the end of the loan, not the beginning.", options:["True","False"], correctIndex:1, explanation:"Points (origination fees) are typically paid upfront at closing, not at loan maturity." },
    { id:111, stage:2, type:"multiple_choice", question:"What is 'interest-only' payment?", options:["You only pay interest each month, not principal","You pay no interest at all","Interest is forgiven"], correctIndex:0, explanation:"Interest-only means monthly payments cover just interest; the principal is paid at maturity." },
    { id:112, stage:2, type:"multiple_choice", question:"A loan with 3 points on $300,000 has an origination fee of:", options:["$3,000","$9,000","$30,000"], correctIndex:1, explanation:"3 points = 3% of $300,000 = $9,000 in origination fees." },
    { id:113, stage:2, type:"true_false", question:"A higher APR always means a worse deal for the borrower.", options:["True","False"], correctIndex:1, explanation:"APR helps compare loans, but a higher APR short-term loan might be better than a lower APR long-term one depending on the deal." },
    { id:114, stage:2, type:"multiple_choice", question:"What is a 'default interest rate'?", options:["The standard rate on the loan","A higher rate charged when the borrower defaults","The lowest rate available"], correctIndex:1, explanation:"Default interest rate is a penalty rate that kicks in when the borrower violates loan terms." },
    { id:115, stage:2, type:"true_false", question:"Some hard money loans charge interest on the full loan amount even if not all funds are drawn.", options:["True","False"], correctIndex:0, explanation:"Some loans charge interest on the full commitment; others only on drawn amounts. It depends on the lender." },
    { id:116, stage:2, type:"multiple_choice", question:"What is 'per diem' interest?", options:["Interest calculated daily","Interest paid once a year","Interest that's forgiven"], correctIndex:0, explanation:"Per diem means 'per day' — it's the daily interest cost, often used for closing calculations." },

    // STAGE 3 EXTRA: Collateral & Secured Lending
    { id:117, stage:3, type:"multiple_choice", question:"What does 'cross-collateralization' mean?", options:["Using one property to secure multiple loans","Using multiple properties to secure one loan","Crossing out the collateral clause"], correctIndex:1, explanation:"Cross-collateralization uses more than one property as security for a single loan." },
    { id:118, stage:3, type:"true_false", question:"A lender can place a lien on personal property, not just real estate.", options:["True","False"], correctIndex:0, explanation:"While hard money focuses on real estate, lenders can sometimes include personal property liens for additional security." },
    { id:119, stage:3, type:"multiple_choice", question:"What is a 'subordinate lien'?", options:["A lien that has lower priority than the first lien","The most important lien","A lien that's been removed"], correctIndex:0, explanation:"A subordinate (junior) lien is behind the first lien in priority for repayment." },
    { id:120, stage:3, type:"multiple_choice", question:"What is a 'blanket loan'?", options:["A loan to buy blankets","A single loan secured by multiple properties","A loan with no collateral"], correctIndex:1, explanation:"A blanket loan covers multiple properties under one mortgage, common in portfolio lending." },
    { id:121, stage:3, type:"true_false", question:"The lender holds physical possession of the collateral property during the loan.", options:["True","False"], correctIndex:1, explanation:"The borrower retains possession and use of the property; the lender holds a lien, not physical possession." },
    { id:122, stage:3, type:"multiple_choice", question:"A 'personal guarantee' means:", options:["The lender guarantees the loan will be approved","The borrower is personally liable beyond just the collateral","The property is guaranteed to increase in value"], correctIndex:1, explanation:"A personal guarantee makes the borrower personally responsible for repayment, beyond just the property." },
    { id:123, stage:3, type:"true_false", question:"Raw land (undeveloped land) can be used as collateral for a hard money loan.", options:["True","False"], correctIndex:0, explanation:"Raw land can serve as collateral, though lenders typically offer lower LTV ratios for undeveloped land." },
    { id:124, stage:3, type:"multiple_choice", question:"What does 'encumbrance' mean in real estate?", options:["A type of renovation","Any claim or lien on a property","A property's age"], correctIndex:1, explanation:"An encumbrance is any right or interest in a property that may diminish its value, like a lien or easement." },

    // STAGE 4 EXTRA: Property Appraisals & Valuations
    { id:125, stage:4, type:"multiple_choice", question:"What is a 'drive-by appraisal'?", options:["An appraisal done from outside the property only","An appraisal done while driving","A fake appraisal"], correctIndex:0, explanation:"A drive-by appraisal is an exterior-only inspection where the appraiser doesn't enter the property." },
    { id:126, stage:4, type:"true_false", question:"An appraisal guarantee means the property will sell for the appraised value.", options:["True","False"], correctIndex:1, explanation:"Appraisals are opinions of value, not guarantees. Market conditions can change rapidly." },
    { id:127, stage:4, type:"multiple_choice", question:"What factors can DECREASE a property's appraised value?", options:["New kitchen renovation","Nearby highway construction and noise","Good school district"], correctIndex:1, explanation:"Negative external factors like noise, pollution, or declining neighborhoods can lower appraised value." },
    { id:128, stage:4, type:"multiple_choice", question:"What is the 'cost approach' to valuation?", options:["How much it costs to buy the property","Estimating value based on the cost to rebuild the structure","The cheapest appraisal method"], correctIndex:1, explanation:"The cost approach values property by calculating land value plus the cost to rebuild the structure minus depreciation." },
    { id:129, stage:4, type:"true_false", question:"Square footage is an important factor in property valuation.", options:["True","False"], correctIndex:0, explanation:"Square footage directly impacts value — price per square foot is a key metric used in comparisons." },
    { id:130, stage:4, type:"multiple_choice", question:"What is 'highest and best use' in appraisal?", options:["The nicest thing about the property","The most profitable legal use of the property","The tallest building allowed"], correctIndex:1, explanation:"Highest and best use is the most profitable, legally permitted, physically possible use of a property." },
    { id:131, stage:4, type:"true_false", question:"An appraisal done 6 months ago is always still valid.", options:["True","False"], correctIndex:1, explanation:"Appraisals have limited shelf life. Most lenders require appraisals less than 90-120 days old." },
    { id:132, stage:4, type:"multiple_choice", question:"What does 'as-is value' mean?", options:["The property's value in its current condition","The value after repairs","The original purchase price"], correctIndex:0, explanation:"As-is value is what the property is worth right now, in its current condition, without any repairs." },

    // STAGE 5 EXTRA: Escrow, Closing & Title
    { id:133, stage:5, type:"multiple_choice", question:"What is a 'title defect'?", options:["A scratch on the property","A problem with the property's ownership history","A building code violation"], correctIndex:1, explanation:"A title defect is an issue in the chain of ownership, like an unresolved lien or missing signature." },
    { id:134, stage:5, type:"true_false", question:"Both buyers and sellers pay closing costs.", options:["True","False"], correctIndex:0, explanation:"Both parties typically have closing costs, though what each pays varies by location and negotiation." },
    { id:135, stage:5, type:"multiple_choice", question:"What is a 'settlement statement'?", options:["A statement settling a dispute","A document listing all costs and credits at closing","A bank statement"], correctIndex:1, explanation:"The settlement statement (like a HUD-1 or Closing Disclosure) itemizes all closing transaction details." },
    { id:136, stage:5, type:"multiple_choice", question:"What is 'chain of title'?", options:["A chain attached to the property deed","The complete history of property ownership transfers","A type of title insurance"], correctIndex:1, explanation:"Chain of title traces ownership from the current owner back through all previous owners." },
    { id:137, stage:5, type:"true_false", question:"A property can have multiple title insurance policies at the same time.", options:["True","False"], correctIndex:0, explanation:"There can be both an owner's policy and a lender's policy on the same property simultaneously." },
    { id:138, stage:5, type:"multiple_choice", question:"What is a 'quitclaim deed'?", options:["A deed that quits the sale","A deed transferring whatever interest the grantor has, with no guarantees","The strongest type of deed"], correctIndex:1, explanation:"A quitclaim deed transfers whatever ownership interest the person has, without warranties." },
    { id:139, stage:5, type:"true_false", question:"Escrow funds earn interest for the escrow company.", options:["True","False"], correctIndex:1, explanation:"Escrow funds are held in trust. In many states, interest earned belongs to the parties, not the escrow company." },
    { id:140, stage:5, type:"multiple_choice", question:"A 'dry closing' means:", options:["A closing where no drinks are served","A closing where documents are signed but funds aren't yet disbursed","A closing in a desert"], correctIndex:1, explanation:"A dry closing occurs when documents are signed but money hasn't yet been transferred or released." },

    // STAGE 6 EXTRA: LTV Ratios & Calculations
    { id:141, stage:6, type:"multiple_choice", question:"A property worth $600,000 with a max LTV of 65% allows a maximum loan of:", options:["$390,000","$420,000","$360,000"], correctIndex:0, explanation:"$600,000 × 65% = $390,000 maximum loan amount." },
    { id:142, stage:6, type:"true_false", question:"LTV and LTARV (Loan-to-After-Repair-Value) are the same thing.", options:["True","False"], correctIndex:1, explanation:"LTV uses current value; LTARV uses the projected value after repairs — they're different calculations." },
    { id:143, stage:6, type:"multiple_choice", question:"If you want a $200,000 loan at 70% LTV, the property must be worth at least:", options:["$285,714","$250,000","$300,000"], correctIndex:0, explanation:"$200,000 ÷ 0.70 = $285,714 minimum property value needed." },
    { id:144, stage:6, type:"multiple_choice", question:"What does a 50% LTV ratio mean?", options:["The loan covers half the property value","The property is worth half of what you paid","You'll pay 50% interest"], correctIndex:0, explanation:"50% LTV means the loan is half the property's value, giving the lender a large equity cushion." },
    { id:145, stage:6, type:"true_false", question:"A higher LTV ratio means more risk for the lender.", options:["True","False"], correctIndex:0, explanation:"Higher LTV means less equity cushion. If the property loses value, the lender may not recover the full loan." },
    { id:146, stage:6, type:"multiple_choice", question:"If a property drops 20% in value and the LTV was 80%, the loan now exceeds the property value. This is called:", options:["Being underwater","Being overfunded","Being overleveraged"], correctIndex:0, explanation:"Being underwater means owing more than the property is worth — a major risk with high LTV loans." },
    { id:147, stage:6, type:"true_false", question:"Hard money lenders sometimes use LTARV instead of LTV for fix-and-flip loans.", options:["True","False"], correctIndex:0, explanation:"LTARV (Loan-to-After-Repair-Value) is common for rehab loans, as it considers the property's future value." },
    { id:148, stage:6, type:"multiple_choice", question:"A $450,000 loan on a $500,000 property has what LTV?", options:["85%","90%","95%"], correctIndex:1, explanation:"$450,000 ÷ $500,000 = 0.90 = 90% LTV. This is very high for hard money lending." },

    // STAGE 7 EXTRA: Defaults, Foreclosure Basics & Risk
    { id:149, stage:7, type:"multiple_choice", question:"What is a 'forbearance agreement'?", options:["A legal term for foreclosure","A temporary pause or reduction in payments agreed by the lender","An agreement to increase the interest rate"], correctIndex:1, explanation:"Forbearance lets the borrower temporarily reduce or pause payments, usually during financial hardship." },
    { id:150, stage:7, type:"true_false", question:"A borrower can cure a default by paying all overdue amounts plus penalties.", options:["True","False"], correctIndex:0, explanation:"Most loans have a cure period where the borrower can fix the default by catching up on payments and fees." },
    { id:151, stage:7, type:"multiple_choice", question:"What is 'risk mitigation' in lending?", options:["Avoiding all loans","Steps taken to reduce potential losses","Charging the highest rate possible"], correctIndex:1, explanation:"Risk mitigation includes strategies like low LTV, property inspections, and strong exit strategies." },
    { id:152, stage:7, type:"multiple_choice", question:"A 'loan-to-cost' ratio measures:", options:["The loan amount vs. total project cost","The loan amount vs. property value","The interest rate vs. inflation"], correctIndex:0, explanation:"Loan-to-cost (LTC) compares the loan to the total cost of acquiring and rehabbing the property." },
    { id:153, stage:7, type:"true_false", question:"Insurance on the collateral property helps protect the lender's investment.", options:["True","False"], correctIndex:0, explanation:"Property insurance protects against physical damage, ensuring the collateral retains its value." },
    { id:154, stage:7, type:"multiple_choice", question:"What happens to a second lien holder if the first lien forecloses?", options:["They get paid first","Their lien may be wiped out","Nothing changes"], correctIndex:1, explanation:"When a first lien forecloses, junior liens are typically extinguished if sale proceeds don't cover them." },
    { id:155, stage:7, type:"true_false", question:"A borrower's credit score is the most important risk factor in hard money lending.", options:["True","False"], correctIndex:1, explanation:"Property value and deal viability are the primary risk factors, not the borrower's credit score." },
    { id:156, stage:7, type:"multiple_choice", question:"What is a 'balloon payment'?", options:["A very small final payment","A large lump sum due at the end of the loan term","A payment made with colorful checks"], correctIndex:1, explanation:"A balloon payment is the large remaining balance due at maturity, common in hard money loans." },

    // STAGE 8 EXTRA: Underwriting & Borrower Evaluation
    { id:157, stage:8, type:"multiple_choice", question:"What is a 'deal analyzer' used for?", options:["Analyzing card games","Evaluating the financial viability of a real estate investment","Checking the borrower's personality"], correctIndex:1, explanation:"A deal analyzer helps determine if a project's numbers make sense — profit margins, costs, and returns." },
    { id:158, stage:8, type:"true_false", question:"A borrower with 10 successful flips is generally considered lower risk.", options:["True","False"], correctIndex:0, explanation:"Experienced borrowers with a proven track record are considered lower risk by hard money lenders." },
    { id:159, stage:8, type:"multiple_choice", question:"What does 'cash reserves' mean in underwriting?", options:["Hidden cash in the walls","Liquid funds the borrower has available after closing","The lender's profit margin"], correctIndex:1, explanation:"Cash reserves show the borrower has money to handle unexpected costs or carry the property." },
    { id:160, stage:8, type:"multiple_choice", question:"An 'inspection draw' is:", options:["A drawing made during inspection","A disbursement of funds after verifying renovation progress","A fee for home inspection"], correctIndex:1, explanation:"Inspection draws release portions of the rehab budget after the lender verifies completed work." },
    { id:161, stage:8, type:"true_false", question:"Lenders may require a contractor's bid or estimate as part of underwriting.", options:["True","False"], correctIndex:0, explanation:"Contractor bids help verify that the renovation budget is realistic and the scope of work is feasible." },
    { id:162, stage:8, type:"multiple_choice", question:"What is a 'holdback' in hard money lending?", options:["Money the borrower holds back from the lender","Funds the lender retains to be released as work progresses","A fee for delaying closing"], correctIndex:1, explanation:"A holdback is money set aside from the loan to be disbursed in stages as renovation milestones are met." },
    { id:163, stage:8, type:"true_false", question:"A borrower's exit strategy of 'sell the property' vs 'refinance' affects the underwriting decision.", options:["True","False"], correctIndex:0, explanation:"The exit strategy determines how and when the lender gets repaid, directly impacting risk assessment." },
    { id:164, stage:8, type:"multiple_choice", question:"What does 'due diligence' mean in lending?", options:["Being polite during the process","Thorough investigation before making a lending decision","The final payment"], correctIndex:1, explanation:"Due diligence is the comprehensive research and analysis done before approving a loan." },

    // STAGE 9 EXTRA: Foreclosure Process & REO
    { id:165, stage:9, type:"multiple_choice", question:"What is a 'lis pendens'?", options:["A type of property lien","A public notice that a lawsuit affecting property has been filed","A foreclosure auction"], correctIndex:1, explanation:"Lis pendens is a recorded notice alerting the public that a legal action involving the property is pending." },
    { id:166, stage:9, type:"true_false", question:"In a judicial foreclosure, the court must approve the foreclosure.", options:["True","False"], correctIndex:0, explanation:"Judicial foreclosure goes through the court system, requiring a judge's approval to proceed." },
    { id:167, stage:9, type:"multiple_choice", question:"What is a 'deficiency judgment'?", options:["A judgment that the property is deficient","A court order requiring the borrower to pay the remaining balance after foreclosure sale","A property inspection report"], correctIndex:1, explanation:"If the foreclosure sale doesn't cover the full loan amount, the lender may seek a deficiency judgment for the difference." },
    { id:168, stage:9, type:"multiple_choice", question:"A 'trustee sale' is associated with:", options:["Judicial foreclosure","Non-judicial foreclosure","Short sales"], correctIndex:1, explanation:"A trustee sale is the auction process in non-judicial foreclosure, conducted by the trustee named in the deed of trust." },
    { id:169, stage:9, type:"true_false", question:"REO properties are typically sold 'as-is' without warranties.", options:["True","False"], correctIndex:0, explanation:"Lenders selling REO properties usually sell them as-is, with no warranties about the property's condition." },
    { id:170, stage:9, type:"multiple_choice", question:"What is a 'right of redemption'?", options:["The right to get a refund on the property","The borrower's right to reclaim the property by paying what's owed","The right to redeem a coupon"], correctIndex:1, explanation:"Right of redemption allows the borrower to reclaim their property by paying the full debt, even after foreclosure in some states." },
    { id:171, stage:9, type:"true_false", question:"All states use the same foreclosure process.", options:["True","False"], correctIndex:1, explanation:"Foreclosure laws vary significantly by state — some use judicial, others non-judicial, with different timelines." },
    { id:172, stage:9, type:"multiple_choice", question:"What is a 'pre-foreclosure'?", options:["A property being sold before it's built","The period between default notice and the actual foreclosure sale","A type of mortgage"], correctIndex:1, explanation:"Pre-foreclosure is the window after the default notice but before the auction, where the borrower can still resolve the debt." },

    // STAGE 10 EXTRA: After Repair Value & Advanced Concepts
    { id:173, stage:10, type:"multiple_choice", question:"Using the 70% rule: ARV is $350K, repairs cost $50K. Max purchase price?", options:["$195,000","$245,000","$200,000"], correctIndex:0, explanation:"($350,000 × 70%) - $50,000 = $245,000 - $50,000 = $195,000." },
    { id:174, stage:10, type:"true_false", question:"Over-improving a property can lead to an ARV that doesn't justify the renovation costs.", options:["True","False"], correctIndex:0, explanation:"Over-improvement means spending more on renovations than the neighborhood can support in resale value." },
    { id:175, stage:10, type:"multiple_choice", question:"What is 'scope creep' in a rehab project?", options:["Bugs in the walls","The project gradually expanding beyond the original plan and budget","A type of property inspection"], correctIndex:1, explanation:"Scope creep happens when unplanned work adds up, increasing costs and timeline beyond original estimates." },
    { id:176, stage:10, type:"multiple_choice", question:"A 'bridge loan' is:", options:["A loan to build a bridge","A short-term loan used until permanent financing is obtained","A loan that connects two bank accounts"], correctIndex:1, explanation:"Bridge loans provide temporary financing to 'bridge' the gap until long-term funding is secured." },
    { id:177, stage:10, type:"true_false", question:"The 70% rule guarantees profit on every flip.", options:["True","False"], correctIndex:1, explanation:"The 70% rule is a guideline, not a guarantee. Unexpected costs, market changes, and holding costs can affect profit." },
    { id:178, stage:10, type:"multiple_choice", question:"What are 'holding costs'?", options:["The cost of holding an open house","Ongoing expenses while owning a property (taxes, insurance, loan payments)","The cost of a property's foundation"], correctIndex:1, explanation:"Holding costs are recurring expenses like mortgage payments, taxes, insurance, and utilities during the project." },
    { id:179, stage:10, type:"true_false", question:"Comparing renovated comps is more useful than unrenovated comps when calculating ARV.", options:["True","False"], correctIndex:0, explanation:"ARV estimates what the property will be worth AFTER renovation, so renovated comparable sales are most relevant." },
    { id:180, stage:10, type:"multiple_choice", question:"What is a 'capital stack' in real estate?", options:["A pile of money","The layers of financing used in a deal (debt, equity, mezzanine)","The total construction cost"], correctIndex:1, explanation:"The capital stack shows all funding sources for a deal — from senior debt to junior debt to equity." },

    // ── SCENARIO-BASED QUESTIONS (Stages 5-10) ──
    // These require applying concepts to real-world situations

    // STAGE 5: Escrow, Closing & Title — Scenarios
    { id:181, stage:5, type:"multiple_choice", question:"A buyer discovers a lien on the property during title search. What should happen?", options:["Close anyway and deal with it later","The lien must be resolved before closing","The buyer automatically gets the lien"], correctIndex:1, explanation:"Liens must be cleared or resolved before closing to ensure the buyer receives clean title." },
    { id:182, stage:5, type:"multiple_choice", question:"Closing costs on a $300,000 hard money loan are 3%. How much does the borrower pay at closing?", options:["$3,000","$9,000","$30,000"], correctIndex:1, explanation:"3% of $300,000 = $9,000 in closing costs paid at the time of closing." },
    { id:183, stage:5, type:"multiple_choice", question:"An escrow officer discovers the seller doesn't actually own the property. What happens?", options:["The deal closes normally","The deal cannot close — seller has no title to transfer","The buyer gets it for free"], correctIndex:1, explanation:"Without valid ownership, the seller cannot legally transfer title. The deal falls through." },
    { id:184, stage:5, type:"true_false", question:"A borrower can skip title insurance to save money on a hard money loan.", options:["True","False"], correctIndex:1, explanation:"Most hard money lenders REQUIRE title insurance to protect their investment against title defects." },
    { id:185, stage:5, type:"multiple_choice", question:"Two people claim ownership of a property. What type of issue is this?", options:["An appraisal issue","A title cloud / defect","An escrow shortage"], correctIndex:1, explanation:"Competing ownership claims create a 'cloud on title' — a defect that must be resolved before the property can be sold." },

    // STAGE 6: LTV Ratios & Calculations — Scenarios
    { id:186, stage:6, type:"multiple_choice", question:"A property is worth $200,000. The borrower wants a $150,000 loan. What is the LTV?", options:["65%","75%","80%"], correctIndex:1, explanation:"LTV = Loan ÷ Value = $150,000 ÷ $200,000 = 0.75 = 75%." },
    { id:187, stage:6, type:"multiple_choice", question:"A lender has a max LTV of 70%. Property value is $400,000. What is the maximum loan amount?", options:["$280,000","$320,000","$400,000"], correctIndex:0, explanation:"Maximum loan = 70% × $400,000 = $280,000." },
    { id:188, stage:6, type:"multiple_choice", question:"A borrower owes $180,000 on a property worth $300,000. They want to refinance. What's the current LTV?", options:["50%","60%","80%"], correctIndex:1, explanation:"Current LTV = $180,000 ÷ $300,000 = 60%." },
    { id:189, stage:6, type:"true_false", question:"A property drops in value from $500K to $400K. If the loan is $350K, the LTV increased.", options:["True","False"], correctIndex:0, explanation:"LTV went from $350K/$500K = 70% to $350K/$400K = 87.5%. Falling property values increase LTV, adding risk." },
    { id:190, stage:6, type:"multiple_choice", question:"Why would a lender prefer an LTV of 65% over 85%?", options:["Higher LTV means less paperwork","Lower LTV means more equity cushion if the borrower defaults","There is no difference"], correctIndex:1, explanation:"Lower LTV = more borrower equity = bigger safety buffer for the lender if they need to foreclose and sell." },

    // STAGE 7: Defaults, Foreclosure & Risk — Scenarios
    { id:191, stage:7, type:"multiple_choice", question:"A borrower misses 3 payments on a $100,000 loan at 12% annual interest. How much interest has accrued?", options:["$1,000","$3,000","$12,000"], correctIndex:1, explanation:"Monthly interest = $100,000 × 1% = $1,000. Three months = $3,000 in unpaid interest." },
    { id:192, stage:7, type:"multiple_choice", question:"A lender forecloses on a property. The loan balance is $250K but the property sells for $200K. Who absorbs the $50K loss?", options:["The borrower must pay it back","The lender takes the loss","The government covers it"], correctIndex:1, explanation:"In most hard money deals, if the foreclosure sale doesn't cover the debt, the lender absorbs the loss (unless they pursue a deficiency judgment)." },
    { id:193, stage:7, type:"true_false", question:"A borrower who defaults on a hard money loan can never get another loan.", options:["True","False"], correctIndex:1, explanation:"While defaults hurt credibility, private lenders may still lend if the deal is strong and the borrower has equity." },
    { id:194, stage:7, type:"multiple_choice", question:"A borrower has a $200K loan with a 3-month extension fee of 1%. What does the extension cost?", options:["$1,000","$2,000","$6,000"], correctIndex:1, explanation:"Extension fee = 1% × $200,000 = $2,000 for the 3-month extension." },
    { id:195, stage:7, type:"multiple_choice", question:"Why do hard money lenders charge higher default interest rates?", options:["To punish borrowers","To compensate for the increased risk and cost of managing delinquent loans","Because banks told them to"], correctIndex:1, explanation:"Default rates cover the lender's additional costs: legal fees, property monitoring, and increased risk of loss." },

    // STAGE 8: Underwriting & Borrower Evaluation — Scenarios
    { id:196, stage:8, type:"multiple_choice", question:"A borrower has flipped 12 houses profitably. Another borrower is a first-timer. Who gets better loan terms?", options:["The first-timer — they need help","The experienced flipper — proven track record reduces risk","Neither — terms are always the same"], correctIndex:1, explanation:"Experience reduces perceived risk. Proven flippers often get lower rates, higher LTV, and faster approvals." },
    { id:197, stage:8, type:"multiple_choice", question:"A borrower wants a $500K loan but only has $25K for a down payment. What's their skin in the game?", options:["5%","25%","50%"], correctIndex:0, explanation:"Skin in the game = $25,000 ÷ $500,000 = 5%. Most hard money lenders want 10-30%, so this borrower may be declined." },
    { id:198, stage:8, type:"true_false", question:"A hard money lender should approve any loan as long as the property value is high enough.", options:["True","False"], correctIndex:1, explanation:"Good underwriting considers the borrower's exit strategy, experience, and ability to complete the project — not just property value." },
    { id:199, stage:8, type:"multiple_choice", question:"A borrower plans to renovate and sell in 6 months, but the loan term is 12 months. Is this a concern?", options:["No — having extra time is always better","Slightly — the exit strategy should align with the term","Yes — the loan should be exactly 6 months"], correctIndex:1, explanation:"Having a realistic timeline with some buffer is fine, but the exit strategy should demonstrate the borrower can repay within the term." },
    { id:200, stage:8, type:"multiple_choice", question:"What is 'liquidity' when evaluating a borrower?", options:["How much water damage the property has","How much cash or accessible funds the borrower has available","The property's resale speed"], correctIndex:1, explanation:"Liquidity refers to how much cash or easily convertible assets the borrower has to cover unexpected costs or payments." },

    // STAGE 9: Foreclosure Process & REO — Scenarios
    { id:201, stage:9, type:"multiple_choice", question:"A bank-owned (REO) property is listed at $150K. Similar properties sell for $200K. Why the discount?", options:["Banks are generous","Banks want to sell quickly and avoid holding costs","The property is always damaged"], correctIndex:1, explanation:"Banks price REO properties to sell fast, minimizing their carrying costs (taxes, maintenance, insurance)." },
    { id:202, stage:9, type:"multiple_choice", question:"Foreclosure takes 6 months. The lender's loan is $200K at 12%. How much interest accrues during foreclosure?", options:["$6,000","$12,000","$24,000"], correctIndex:1, explanation:"6 months × ($200,000 × 12% ÷ 12) = 6 × $2,000 = $12,000 in interest during the foreclosure process." },
    { id:203, stage:9, type:"true_false", question:"Buying a property at a foreclosure auction always means getting a great deal.", options:["True","False"], correctIndex:1, explanation:"Auction properties may have hidden liens, damage, or occupants. Due diligence is limited, so deals can be risky." },
    { id:204, stage:9, type:"multiple_choice", question:"A property goes to auction but nobody bids. What happens?", options:["It gets demolished","The lender takes ownership and it becomes REO","The borrower gets it back"], correctIndex:1, explanation:"If no one bids at auction, the lender takes ownership. The property becomes 'Real Estate Owned' (REO)." },
    { id:205, stage:9, type:"multiple_choice", question:"A hard money lender forecloses in a judicial state. What does 'judicial' mean?", options:["The foreclosure goes through the court system","A judge buys the property","The lender doesn't need permission"], correctIndex:0, explanation:"In judicial foreclosure states, the lender must file a lawsuit and get court approval to foreclose, which takes longer." },

    // STAGE 10: ARV & Advanced — Scenarios
    { id:206, stage:10, type:"multiple_choice", question:"A property's current value is $120K. Repairs cost $40K. Comparable renovated homes sell for $220K. What's the ARV?", options:["$160,000","$180,000","$220,000"], correctIndex:2, explanation:"ARV is what the property will be worth AFTER repairs, based on comparable sales = $220,000. It's not current value + repairs." },
    { id:207, stage:10, type:"multiple_choice", question:"Using the 70% rule: ARV is $300K, repairs are $50K. What's the max purchase price?", options:["$160,000","$210,000","$250,000"], correctIndex:0, explanation:"70% rule: Max price = (ARV × 70%) - repairs = ($300,000 × 0.70) - $50,000 = $210,000 - $50,000 = $160,000." },
    { id:208, stage:10, type:"multiple_choice", question:"An investor buys for $150K, spends $60K on repairs, and sells for $280K. What's the gross profit?", options:["$70,000","$90,000","$130,000"], correctIndex:0, explanation:"Gross profit = Sale price - Purchase - Repairs = $280K - $150K - $60K = $70,000 (before closing costs and fees)." },
    { id:209, stage:10, type:"true_false", question:"A property's ARV can change based on market conditions between purchase and sale.", options:["True","False"], correctIndex:0, explanation:"ARV is an estimate. If the market rises or falls during renovation, the actual sale price may differ from the original ARV." },
    { id:210, stage:10, type:"multiple_choice", question:"An investor's total project cost is $200K. They sell for $260K but pay $15K in closing/holding costs. Net profit?", options:["$45,000","$60,000","$75,000"], correctIndex:0, explanation:"Net profit = $260K - $200K - $15K = $45,000. Always subtract ALL costs, not just purchase and repairs." }
];
