export const STAGE_TOPICS = {
    1: 'Basic Lending Terms',
    2: 'Interest Rates & APR',
    3: 'Collateral & Secured Lending',
    4: 'Property Appraisals & Valuations',
    5: 'Escrow, Closing & Title',
    6: 'LTV Ratios & Calculations',
    7: 'Defaults, Foreclosure Basics & Risk',
    8: 'Underwriting & Borrower Evaluation',
    9: 'Foreclosure Process & REO',
    10: 'After Repair Value & Advanced Concepts'
};

export const QUESTIONS = [
    // STAGE 1: The Loan Goblin - Basic Lending Terms
    { id:1, stage:1, type:"multiple_choice", question:"What is a hard money loan?", options:["A short-term loan secured by real property","A government-backed student loan","A credit card cash advance"], correctIndex:0, explanation:"Hard money loans are short-term loans backed by real estate, funded by private investors." },
    { id:2, stage:1, type:"true_false", question:"Hard money loans are typically funded by banks.", options:["True","False"], correctIndex:1, explanation:"Hard money loans are funded by private investors or companies, not traditional banks." },
    { id:3, stage:1, type:"multiple_choice", question:"What does 'principal' mean in lending?", options:["The interest rate","The original amount borrowed","The monthly payment"], correctIndex:1, explanation:"Principal is the original sum of money borrowed, before interest." },
    { id:4, stage:1, type:"true_false", question:"Hard money loans are usually short-term (1-3 years).", options:["True","False"], correctIndex:0, explanation:"Most hard money loans have terms of 6 months to 3 years." },
    { id:5, stage:1, type:"multiple_choice", question:"Who is the 'borrower' in a loan?", options:["The person lending money","The person receiving the loan","The real estate agent"], correctIndex:1, explanation:"The borrower is the person or entity that receives the loan funds." },
    { id:6, stage:1, type:"multiple_choice", question:"What is another name for the lender in hard money?", options:["Private lender","Federal agent","Mortgage broker"], correctIndex:0, explanation:"Hard money lenders are often called private lenders since they use private capital." },
    { id:7, stage:1, type:"true_false", question:"Hard money loans can close faster than bank loans.", options:["True","False"], correctIndex:0, explanation:"Hard money loans can close in days, while bank loans often take 30-60 days." },
    { id:8, stage:1, type:"multiple_choice", question:"What does 'term' mean for a loan?", options:["The interest rate charged","The length of time to repay","The property address"], correctIndex:1, explanation:"The term is the duration of the loan — how long you have to repay it." },
    { id:9, stage:1, type:"multiple_choice", question:"Hard money loans are most commonly used for:", options:["Buying groceries","Real estate investments","Paying off student loans"], correctIndex:1, explanation:"Hard money loans are primarily used for real estate investment and property transactions." },
    { id:10, stage:1, type:"true_false", question:"A promissory note is a written promise to repay a loan.", options:["True","False"], correctIndex:0, explanation:"A promissory note is a legal document where the borrower promises to repay the lender." },

    // STAGE 2: The Interest Rate Imp - Interest Rates & APR
    { id:11, stage:2, type:"multiple_choice", question:"Typical hard money interest rates are:", options:["1-3%","8-15%","25-30%"], correctIndex:1, explanation:"Hard money loans typically carry interest rates between 8% and 15%." },
    { id:12, stage:2, type:"multiple_choice", question:"What does APR stand for?", options:["Annual Percentage Rate","Approved Property Rating","Adjusted Payment Ratio"], correctIndex:0, explanation:"APR stands for Annual Percentage Rate — the total yearly cost of borrowing." },
    { id:13, stage:2, type:"true_false", question:"APR includes both interest and fees.", options:["True","False"], correctIndex:0, explanation:"APR reflects the true cost of borrowing by including interest rate plus fees." },
    { id:14, stage:2, type:"multiple_choice", question:"What is 1 'point' on a loan?", options:["1% of the loan amount","$1,000 flat fee","1% of the property value"], correctIndex:0, explanation:"One point equals 1% of the loan amount, charged as an upfront fee." },
    { id:15, stage:2, type:"multiple_choice", question:"If you borrow $200,000 and pay 2 points, what's the fee?", options:["$2,000","$4,000","$20,000"], correctIndex:1, explanation:"2 points on $200,000 = 2% × $200,000 = $4,000." },
    { id:16, stage:2, type:"true_false", question:"Hard money rates are usually lower than bank rates.", options:["True","False"], correctIndex:1, explanation:"Hard money rates are higher than bank rates because of faster funding and higher risk." },
    { id:17, stage:2, type:"multiple_choice", question:"Why are hard money rates higher than bank rates?", options:["Lenders are greedy","Higher risk and faster funding","Government regulations"], correctIndex:1, explanation:"The higher rates compensate for increased risk and the speed of private lending." },
    { id:18, stage:2, type:"true_false", question:"Interest on hard money loans can be paid monthly or at maturity.", options:["True","False"], correctIndex:0, explanation:"Some hard money loans require monthly interest payments, others collect all interest at payoff." },
    { id:19, stage:2, type:"multiple_choice", question:"What is a 'prepayment penalty'?", options:["A fee for paying late","A fee for paying off the loan early","A fee for the appraisal"], correctIndex:1, explanation:"A prepayment penalty is charged when a borrower pays off the loan before the term ends." },
    { id:20, stage:2, type:"multiple_choice", question:"If a loan has 12% annual interest, what is the monthly rate?", options:["1%","6%","12%"], correctIndex:0, explanation:"Monthly rate = Annual rate ÷ 12, so 12% ÷ 12 = 1% per month." },

    // STAGE 3: The Collateral Crab - Collateral & Secured Lending
    { id:21, stage:3, type:"multiple_choice", question:"What is collateral?", options:["A type of insurance","An asset pledged to secure a loan","A closing document"], correctIndex:1, explanation:"Collateral is property or assets that a borrower offers to secure a loan." },
    { id:22, stage:3, type:"true_false", question:"Hard money loans are secured by real property.", options:["True","False"], correctIndex:0, explanation:"The real estate itself serves as collateral for hard money loans." },
    { id:23, stage:3, type:"multiple_choice", question:"What happens if a borrower defaults on a secured loan?", options:["Nothing happens","The lender can take the collateral","The rate goes down"], correctIndex:1, explanation:"If a borrower defaults, the lender can seize the collateral (the property) to recover the loan." },
    { id:24, stage:3, type:"multiple_choice", question:"A lien is:", options:["A type of property","A legal claim on property as security for a debt","A discount on the loan"], correctIndex:1, explanation:"A lien gives the lender a legal right to the property until the debt is paid." },
    { id:25, stage:3, type:"true_false", question:"Hard money lenders care more about the property than the borrower's credit score.", options:["True","False"], correctIndex:0, explanation:"Hard money lending is asset-based — the property value matters more than credit scores." },
    { id:26, stage:3, type:"multiple_choice", question:"What is a first lien position?", options:["The newest loan on a property","The loan with highest priority to be repaid","The smallest loan"], correctIndex:1, explanation:"First lien has priority — it gets paid first if the property is sold or foreclosed." },
    { id:27, stage:3, type:"true_false", question:"An unsecured loan has no collateral backing it.", options:["True","False"], correctIndex:0, explanation:"Unsecured loans have no collateral, unlike hard money loans which are always secured." },
    { id:28, stage:3, type:"multiple_choice", question:"What type of property can be used as collateral?", options:["Only single-family homes","Only commercial buildings","Residential, commercial, and land"], correctIndex:2, explanation:"Various property types can serve as collateral including homes, commercial, and raw land." },
    { id:29, stage:3, type:"true_false", question:"A second lien is riskier for the lender than a first lien.", options:["True","False"], correctIndex:0, explanation:"Second lien holders get paid after first lien holders, making it a riskier position." },
    { id:30, stage:3, type:"multiple_choice", question:"A deed of trust:", options:["Transfers property to the buyer","Secures the loan against the property","Is the same as a lease"], correctIndex:1, explanation:"A deed of trust is a security instrument that ties the loan to the property." },

    // STAGE 4: The Appraisal Ghost - Property Appraisals & Valuations
    { id:31, stage:4, type:"multiple_choice", question:"What is a property appraisal?", options:["A home inspection for defects","A professional estimate of a property's market value","A title search"], correctIndex:1, explanation:"An appraisal determines the fair market value of a property by a licensed appraiser." },
    { id:32, stage:4, type:"true_false", question:"Comparable sales (comps) are used to determine property value.", options:["True","False"], correctIndex:0, explanation:"Appraisers use recent sales of similar nearby properties to estimate value." },
    { id:33, stage:4, type:"multiple_choice", question:"What are 'comps' in real estate?", options:["Complaints about a property","Recently sold similar properties nearby","Computer-generated estimates"], correctIndex:1, explanation:"Comps are comparable properties that recently sold, used to estimate market value." },
    { id:34, stage:4, type:"multiple_choice", question:"Why do hard money lenders require appraisals?", options:["It's a way to charge more fees","To ensure the property value covers the loan","For decoration"], correctIndex:1, explanation:"Lenders need to verify the property is worth enough to secure the loan amount." },
    { id:35, stage:4, type:"true_false", question:"An appraisal and a home inspection are the same thing.", options:["True","False"], correctIndex:1, explanation:"An appraisal determines value; an inspection checks the physical condition of the property." },
    { id:36, stage:4, type:"multiple_choice", question:"Fair Market Value (FMV) is:", options:["The price a seller hopes to get","The price a willing buyer and seller agree upon","The original purchase price"], correctIndex:1, explanation:"FMV is what a property would sell for on the open market between willing parties." },
    { id:37, stage:4, type:"true_false", question:"A property's assessed value for taxes is always the same as its market value.", options:["True","False"], correctIndex:1, explanation:"Tax assessed value and market value are often different — assessed value may be lower." },
    { id:38, stage:4, type:"multiple_choice", question:"A BPO stands for:", options:["Broker Price Opinion","Bank Payment Order","Buyer's Purchase Offer"], correctIndex:0, explanation:"A BPO is a less formal property valuation done by a real estate broker." },
    { id:39, stage:4, type:"multiple_choice", question:"If similar homes in the area sold for $300K, $310K, and $290K, the property is likely worth around:", options:["$200,000","$300,000","$500,000"], correctIndex:1, explanation:"Comps averaging around $300K suggest the property value is in that range." },
    { id:40, stage:4, type:"true_false", question:"Location is one of the most important factors in property valuation.", options:["True","False"], correctIndex:0, explanation:"Location significantly impacts property value — it's the #1 factor in real estate." },

    // STAGE 5: The Escrow Ogre - Escrow, Closing & Title
    { id:41, stage:5, type:"multiple_choice", question:"What is escrow?", options:["A type of loan","A neutral third party that holds funds during a transaction","A property tax"], correctIndex:1, explanation:"Escrow is a neutral party that holds money and documents until all deal conditions are met." },
    { id:42, stage:5, type:"true_false", question:"Title insurance protects against ownership disputes.", options:["True","False"], correctIndex:0, explanation:"Title insurance protects the buyer and lender from claims against the property's ownership." },
    { id:43, stage:5, type:"multiple_choice", question:"What is a title search?", options:["Searching for a property online","Examining public records for ownership history","Choosing a name for your property"], correctIndex:1, explanation:"A title search reviews public records to verify clear ownership and find any liens." },
    { id:44, stage:5, type:"multiple_choice", question:"'Closing' in real estate refers to:", options:["Shutting down a property","The final step where ownership transfers","Closing a bank account"], correctIndex:1, explanation:"Closing is the final meeting where documents are signed and ownership officially transfers." },
    { id:45, stage:5, type:"true_false", question:"Closing costs only include the lender's fees.", options:["True","False"], correctIndex:1, explanation:"Closing costs include lender fees, title fees, escrow fees, recording fees, and more." },
    { id:46, stage:5, type:"multiple_choice", question:"A clear title means:", options:["The property has a nice name","There are no liens or ownership disputes","The house was recently painted"], correctIndex:1, explanation:"A clear title means no legal claims, liens, or disputes exist against the property." },
    { id:47, stage:5, type:"multiple_choice", question:"Who typically chooses the escrow company?", options:["The government","Usually agreed upon by buyer and seller","The neighbors"], correctIndex:1, explanation:"The escrow company is typically chosen by agreement between the parties in the transaction." },
    { id:48, stage:5, type:"true_false", question:"Recording a deed makes the property transfer part of public record.", options:["True","False"], correctIndex:0, explanation:"Recording the deed with the county officially documents the change of ownership." },
    { id:49, stage:5, type:"multiple_choice", question:"What is earnest money?", options:["Money the lender earns","A good-faith deposit from the buyer","The appraiser's fee"], correctIndex:1, explanation:"Earnest money shows the buyer is serious — it's a deposit held in escrow." },
    { id:50, stage:5, type:"true_false", question:"You can close on a hard money loan without an escrow company.", options:["True","False"], correctIndex:1, explanation:"Escrow companies are typically required to ensure a safe and proper closing process." },

    // STAGE 6: The LTV Werewolf - LTV Ratios & Calculations
    { id:51, stage:6, type:"multiple_choice", question:"What does LTV stand for?", options:["Loan-To-Value","Long-Term Variance","Lender Tax Verification"], correctIndex:0, explanation:"LTV stands for Loan-To-Value — the ratio of the loan amount to the property value." },
    { id:52, stage:6, type:"multiple_choice", question:"How do you calculate LTV?", options:["Property Value ÷ Loan Amount","Loan Amount ÷ Property Value","Loan Amount × Interest Rate"], correctIndex:1, explanation:"LTV = Loan Amount ÷ Property Value. A $150K loan on a $200K property = 75% LTV." },
    { id:53, stage:6, type:"true_false", question:"A lower LTV means less risk for the lender.", options:["True","False"], correctIndex:0, explanation:"Lower LTV means the loan is a smaller portion of the property value — more equity cushion." },
    { id:54, stage:6, type:"multiple_choice", question:"Most hard money lenders cap LTV at:", options:["90-100%","60-75%","10-20%"], correctIndex:1, explanation:"Hard money lenders typically lend up to 60-75% of the property's value." },
    { id:55, stage:6, type:"multiple_choice", question:"A $300,000 loan on a $400,000 property has what LTV?", options:["75%","60%","80%"], correctIndex:0, explanation:"$300,000 ÷ $400,000 = 0.75 = 75% LTV." },
    { id:56, stage:6, type:"true_false", question:"100% LTV means the loan covers the entire property value.", options:["True","False"], correctIndex:0, explanation:"100% LTV means no down payment — the loan equals the full property value (very risky)." },
    { id:57, stage:6, type:"multiple_choice", question:"If a property is worth $500,000 and the max LTV is 70%, what's the maximum loan?", options:["$350,000","$500,000","$250,000"], correctIndex:0, explanation:"$500,000 × 70% = $350,000 maximum loan amount." },
    { id:58, stage:6, type:"multiple_choice", question:"Why do hard money lenders keep LTV low?", options:["To annoy borrowers","To protect against losses if they need to sell the property","Because the law requires it"], correctIndex:1, explanation:"Low LTV ensures the lender can recover their money even if the property loses value." },
    { id:59, stage:6, type:"true_false", question:"A borrower's down payment reduces the LTV ratio.", options:["True","False"], correctIndex:0, explanation:"A larger down payment means a smaller loan relative to value — lower LTV." },
    { id:60, stage:6, type:"multiple_choice", question:"CLTV stands for:", options:["Combined Loan-To-Value","Current Lending Tax Value","Closed Loan Transfer Voucher"], correctIndex:0, explanation:"CLTV is Combined Loan-To-Value — it includes all loans against the property." },

    // STAGE 7: The Default Demon - Defaults, Foreclosure Basics & Risk
    { id:61, stage:7, type:"multiple_choice", question:"What does it mean to 'default' on a loan?", options:["To pay it off early","To fail to meet loan obligations","To refinance the loan"], correctIndex:1, explanation:"Default means the borrower has failed to make payments or meet other loan terms." },
    { id:62, stage:7, type:"true_false", question:"Missing one payment immediately triggers foreclosure.", options:["True","False"], correctIndex:1, explanation:"Typically lenders provide a grace period and notice before starting foreclosure proceedings." },
    { id:63, stage:7, type:"multiple_choice", question:"What is the main risk for a hard money lender?", options:["The borrower being too nice","The borrower defaulting and the property losing value","Interest rates going up"], correctIndex:1, explanation:"The biggest risk is default combined with a property worth less than the loan balance." },
    { id:64, stage:7, type:"multiple_choice", question:"A 'maturity default' occurs when:", options:["The borrower is too old","The loan term expires and the borrower can't repay","The property matures in value"], correctIndex:1, explanation:"Maturity default happens when the loan term ends and the borrower cannot pay it off." },
    { id:65, stage:7, type:"true_false", question:"Hard money lenders mitigate risk by keeping LTV ratios low.", options:["True","False"], correctIndex:0, explanation:"Low LTV ratios provide an equity cushion, reducing the lender's risk of loss." },
    { id:66, stage:7, type:"multiple_choice", question:"What is a loan modification?", options:["Changing the property","Changing the loan terms to help the borrower","Changing the lender"], correctIndex:1, explanation:"A loan modification adjusts terms like rate or duration to help a struggling borrower." },
    { id:67, stage:7, type:"true_false", question:"Diversifying across multiple loans reduces a lender's risk.", options:["True","False"], correctIndex:0, explanation:"Spreading investments across multiple loans means one default doesn't wipe out the lender." },
    { id:68, stage:7, type:"multiple_choice", question:"A 'notice of default' is:", options:["A friendly reminder","A formal notification that the borrower has violated loan terms","A receipt for payment"], correctIndex:1, explanation:"A notice of default is a formal document starting the pre-foreclosure process." },
    { id:69, stage:7, type:"multiple_choice", question:"What is an 'exit strategy'?", options:["A plan to leave a building","The borrower's plan to repay the loan","A type of insurance"], correctIndex:1, explanation:"An exit strategy is how the borrower plans to pay off the loan (sell, refinance, etc.)." },
    { id:70, stage:7, type:"true_false", question:"A borrower's exit strategy is important to hard money lenders.", options:["True","False"], correctIndex:0, explanation:"Lenders want to know how the borrower will repay — a clear exit strategy reduces risk." },

    // STAGE 8: The Underwriting Hydra - Underwriting & Borrower Evaluation
    { id:71, stage:8, type:"multiple_choice", question:"What is underwriting?", options:["Writing under a document","The process of evaluating loan risk","Signing the bottom of a check"], correctIndex:1, explanation:"Underwriting is the process of assessing the risk of making a loan." },
    { id:72, stage:8, type:"true_false", question:"Hard money underwriting focuses more on the property than the borrower's credit.", options:["True","False"], correctIndex:0, explanation:"Unlike banks, hard money lenders primarily evaluate the property and deal, not credit scores." },
    { id:73, stage:8, type:"multiple_choice", question:"What is a key factor in hard money underwriting?", options:["The borrower's favorite color","The property value and condition","The borrower's age"], correctIndex:1, explanation:"Property value, condition, and the deal's viability are the primary underwriting factors." },
    { id:74, stage:8, type:"multiple_choice", question:"A borrower's 'track record' refers to:", options:["Their running speed","Their experience with similar deals","Their music playlist"], correctIndex:1, explanation:"Experienced borrowers with successful past deals are considered lower risk." },
    { id:75, stage:8, type:"true_false", question:"Hard money lenders never look at a borrower's credit at all.", options:["True","False"], correctIndex:1, explanation:"While not the primary focus, many hard money lenders do a basic credit check." },
    { id:76, stage:8, type:"multiple_choice", question:"What does 'skin in the game' mean for a borrower?", options:["They have a sunburn","They have their own money invested in the deal","They work in a leather shop"], correctIndex:1, explanation:"Skin in the game means the borrower has invested their own capital, aligning interests." },
    { id:77, stage:8, type:"multiple_choice", question:"A 'scope of work' in hard money lending describes:", options:["The lender's job duties","The planned renovations and their costs","The borrower's employment history"], correctIndex:1, explanation:"The scope of work details what repairs/renovations will be done and at what cost." },
    { id:78, stage:8, type:"true_false", question:"A borrower's exit strategy is part of the underwriting process.", options:["True","False"], correctIndex:0, explanation:"Lenders evaluate the exit strategy to determine how and when they'll be repaid." },
    { id:79, stage:8, type:"multiple_choice", question:"Draw schedules are used to:", options:["Create artwork","Release renovation funds in stages as work is completed","Schedule meetings"], correctIndex:1, explanation:"Draw schedules release loan funds incrementally as renovation milestones are completed." },
    { id:80, stage:8, type:"true_false", question:"A hard money lender might inspect the property during renovation.", options:["True","False"], correctIndex:0, explanation:"Lenders often inspect progress before releasing additional renovation funds." },

    // STAGE 9: The Foreclosure Phoenix - Foreclosure Process & REO
    { id:81, stage:9, type:"multiple_choice", question:"What is foreclosure?", options:["Closing a gate","The legal process of taking property from a defaulted borrower","A type of insurance claim"], correctIndex:1, explanation:"Foreclosure is the legal process where a lender takes ownership of property after default." },
    { id:82, stage:9, type:"multiple_choice", question:"What does REO stand for?", options:["Real Estate Owned","Really Expensive Offer","Regional Escrow Office"], correctIndex:0, explanation:"REO means Real Estate Owned — property owned by a lender after a failed foreclosure auction." },
    { id:83, stage:9, type:"true_false", question:"There are two types of foreclosure: judicial and non-judicial.", options:["True","False"], correctIndex:0, explanation:"Judicial foreclosure goes through court; non-judicial follows a power of sale clause." },
    { id:84, stage:9, type:"multiple_choice", question:"A foreclosure auction is:", options:["A party at the courthouse","A public sale of the foreclosed property","A private meeting with the borrower"], correctIndex:1, explanation:"At a foreclosure auction, the property is sold to the highest bidder to repay the debt." },
    { id:85, stage:9, type:"true_false", question:"The borrower can sometimes stop foreclosure by paying what's owed.", options:["True","False"], correctIndex:0, explanation:"Many states allow a redemption period where the borrower can pay off the debt to keep the property." },
    { id:86, stage:9, type:"multiple_choice", question:"A 'short sale' happens when:", options:["The sale takes a short time","The property sells for less than the loan balance with lender approval","The seller is short"], correctIndex:1, explanation:"In a short sale, the lender agrees to accept less than what's owed to avoid foreclosure." },
    { id:87, stage:9, type:"multiple_choice", question:"What is a 'deed in lieu of foreclosure'?", options:["A special type of deed","The borrower voluntarily transfers the property to the lender","A fake deed"], correctIndex:1, explanation:"A deed in lieu lets the borrower hand over the property to avoid formal foreclosure." },
    { id:88, stage:9, type:"true_false", question:"Foreclosure timelines vary by state.", options:["True","False"], correctIndex:0, explanation:"Each state has different foreclosure laws, and timelines can range from weeks to over a year." },
    { id:89, stage:9, type:"multiple_choice", question:"A 'workout' in lending means:", options:["Going to the gym","Negotiating alternatives to foreclosure","Working overtime"], correctIndex:1, explanation:"A workout is when lender and borrower negotiate alternatives like modification or repayment plans." },
    { id:90, stage:9, type:"true_false", question:"REO properties are often sold at a discount.", options:["True","False"], correctIndex:0, explanation:"REO properties often sell below market value since lenders want to recover their capital quickly." },

    // STAGE 10: The ARV Dragon - After Repair Value & Advanced Concepts
    { id:91, stage:10, type:"multiple_choice", question:"What does ARV stand for?", options:["After Repair Value","Annual Rate of Variance","Adjusted Real Value"], correctIndex:0, explanation:"ARV is the estimated value of a property AFTER renovations are completed." },
    { id:92, stage:10, type:"multiple_choice", question:"The 70% Rule says investors should pay no more than:", options:["70% of current value","70% of ARV minus repair costs","70% of the loan amount"], correctIndex:1, explanation:"The 70% Rule: Max Purchase = (ARV × 70%) - Repair Costs." },
    { id:93, stage:10, type:"true_false", question:"ARV is calculated BEFORE renovations are done.", options:["True","False"], correctIndex:0, explanation:"ARV is an estimate made before work begins, projecting what the property will be worth after." },
    { id:94, stage:10, type:"multiple_choice", question:"If a property has an ARV of $400,000, what's the max loan at 70% LTV?", options:["$280,000","$320,000","$400,000"], correctIndex:0, explanation:"$400,000 × 70% = $280,000 maximum loan amount." },
    { id:95, stage:10, type:"multiple_choice", question:"A 'fix and flip' strategy is:", options:["Fixing a pancake","Buying, renovating, and selling a property for profit","Flipping a coin to decide"], correctIndex:1, explanation:"Fix and flip means purchasing a property, renovating it, and selling at a higher price." },
    { id:96, stage:10, type:"true_false", question:"ARV is determined using comps of renovated properties in the area.", options:["True","False"], correctIndex:0, explanation:"ARV uses comparable sales of similar renovated properties to estimate post-repair value." },
    { id:97, stage:10, type:"multiple_choice", question:"Using the 70% rule: ARV is $500K, repairs cost $80K. Max purchase price?", options:["$270,000","$350,000","$420,000"], correctIndex:0, explanation:"($500,000 × 70%) - $80,000 = $350,000 - $80,000 = $270,000." },
    { id:98, stage:10, type:"multiple_choice", question:"What is a BRRRR strategy?", options:["Being cold","Buy, Rehab, Rent, Refinance, Repeat","Borrow, Return, Reinvest, Redo, Relax"], correctIndex:1, explanation:"BRRRR is a real estate strategy: Buy, Rehab, Rent, Refinance, and Repeat." },
    { id:99, stage:10, type:"true_false", question:"Hard money loans are commonly used to fund fix-and-flip projects.", options:["True","False"], correctIndex:0, explanation:"Fix-and-flip is one of the most common uses for hard money loans due to their short-term nature." },
    { id:100, stage:10, type:"multiple_choice", question:"What is 'equity' in a property?", options:["The property's total value","The difference between property value and what's owed","The monthly payment amount"], correctIndex:1, explanation:"Equity = Property Value - Loan Balance. It's the owner's actual stake in the property." }
];
